# Introdução a biblioteca NumPy

In [2]:
# Importando a biblioteca numpy
import numpy as np

In [ ]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [ ]:
# Imprimindo um array
print(type(one_dim))
print(one_dim.ndim)

In [4]:
# Criando um array de 2 dimensões
two_dim = np.array([(1,2,3),(4,5,6), (7,8,9)])

# Imprimindo um array
print(two_dim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Cria um array de numeros aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

In [ ]:
# Cria um array com valores esparsos iniciando com valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

In [ ]:
#Cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

In [ ]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões
np.zeros((3,4))

In [ ]:
# Criando um lista
lista = [1,2,3]

In [ ]:
# Multiplicando valores da lista por 2, ou seja repete os valores.
lista * 2

In [ ]:
#Transformando a lista em um array Numpy
lista = np.array(lista)

In [ ]:
# Imprimindo o tipo atual da lista
type(lista)

In [ ]:
# Multiplicando cada elemento por 2
lista * 2

In [ ]:
# Calcular IMC de pessoas
pesos = [67, 81, 120, 90]
altura = [1.68, 1.70, 1.75, 1.85]

In [ ]:
# Faz o calculo usando as listas
pesos / altura ** 2

In [ ]:
# Transformar as listas em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
# Imprime o calculo de cada valor
pesos / altura ** 2

In [ ]:
# Arrays Numpy armazenam todos os elementos como strings quando algum item não é inteiro ou float
a = np.array([1,3,'Casa',True])

In [ ]:
a

# Métodos e Atributos

In [147]:
# Retorna a quantidade de linhas e colunas do array
two_dim.shape

(3, 3)

In [148]:
# Retorna a quantidade de dimensões do array
two_dim.ndim

2

In [ ]:
# Retorna o valor o maior valor do array
two_dim.max()

In [ ]:
# Retorna o valor o menor valor do array
two_dim.min()

In [ ]:
# Retorna o valor médio valor do array
two_dim.mean()

In [149]:
# Retorna o desvio padrão
two_dim.std()

2.581988897471611

In [150]:
# Retorna o tipo de dados do array
two_dim.dtype

dtype('int64')

In [151]:
# Retorna a quantidade de elementos do array
two_dim.size

9

In [ ]:
# Soma todos os elementos do array
two_dim.sum()

In [ ]:
# Gera a Transposta da matriz, ou seja, linha se torna coluna e vice versa.
two_dim.T

In [ ]:
# Trasforma numa matriz de 1 linha
two_dim.reshape(-1)

In [ ]:
# Cria uma matriz de números aleatórios de 5 linhas e 3 colunas
tree = np.random.random((5,3))
tree

In [ ]:
# Mostra a quantidade de linhas e colunas da matriz
tree.shape

In [ ]:
# Reorganiza a matriz em 1 linha com 15 colunas
t = tree.reshape(1,15)
t.shape

In [ ]:
# Adiciona elementos ao array
two_dim = np.insert(two_dim, 0, 10)
two_dim

In [ ]:
# Deleta um elemento do array na posição [indice].
two_dim = np.delete(two_dim, [2])
two_dim

In [ ]:
# Gera um arquivo .txt a partir de um array
np.savetxt('dataset_array.txt', two_dim, delimiter=',')

In [6]:
# Retorna uma posição de linha e coluna pelo valor do elemento
index = np.where(two_dim == 5)
index

(array([1]), array([1]))

In [7]:
# Retorna a linha em que se encontra o elemento
index[0]

array([1])

In [8]:
# Retorna a coluna em que se encontra o elemento
index[1]

array([1])

# Acessando Dimensões no Array

In [ ]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha, coluna
my_array = np.random.random([10,2])
my_array

In [ ]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

In [145]:
# Imprimindo o elemento da posição linha 0 e coluna 0
my_array[0][0]

0.4876801753953971

In [ ]:
# Imprimindo o elemento da posição linha 0 e coluna 1
my_array[0][1]

In [ ]:
# Imprimindo o elemento da posição linha 1 e coluna 1
my_array[1][1]

In [ ]:
# Segundo elemento da coluna escrito com virgula
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

In [ ]:
# Imprime até 3 valores da coluna 1
my_array[:3,1]

In [ ]:
# Imprime todos os valores da coluna 2 * 10
my_array[:,1] * 10

In [ ]:
# Comparação, retorna um valor booleano para cada elemento com base na condição
my_array > 0.50

In [ ]:
# Retorna os valores que atendem a condição
my_array[my_array > 0.50]

# Carregar arrays Numpy a partir de arquivos de Texto

In [ ]:
# Ler um arquivo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [ ]:
dataset.shape

In [ ]:
# Carregar um arquivo e dividir em 3 arrays
a, b, c = np.loadtxt('dataset_array.txt', skipprows=1, unpack=True)

In [ ]:
# array a
a

In [ ]:
# array b
b

In [ ]:
# array c
c